# Generated by Django 4.1.7 on 2023-04-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message_rename_email_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageToSubscribe',
        ),
    ]
