# Generated by Django 4.1.7 on 2023-04-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_message_messagetosubscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetosubscribe',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messagetosubscribe',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='messagetosubscribe',
            name='summary',
        ),
    ]
