# Generated by Django 4.1.7 on 2023-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_text_messagetosubscribe_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
